version: '3'
services:
  web:
    build: ./
    depends_on:
      - db
    container_name: 'apache'
    ports:
      - '80:80'
    volumes: 
      - './html/web:/var/www/html'
      - './conf/000-default.conf:/etc/apache2/sites-available/000-default.conf'
    networks:
      net:
        ipv4_address: 172.31.0.2
  db:
    build: ./mysql/
    container_name: 'mysql'
    volumes:
      - ./html/bbdd.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - '3333:3306'
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_DATABASE=cmsofuscado
      - MYSQL_USER=cmsofuscado
      - MYSQL_PASSWORD=xxxx
    networks:
      net:
        ipv4_address: 172.31.0.3
networks: 
  net:
    ipam:
      driver: default
      config: 
        - subnet: "172.31.0.0/24"
      
